services:
  - type: web
    name: fraudlens
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        sync: false
      - key: MYSQL_PORT
        sync: false
